- name: setup local development environment
  remote_user: root
  hosts: all
  tasks:
  - name: install common applications
    apt:
      name:
      - audacity                      # simple audio editor
      - bleachbit                     # computer cleaner
      - blender                       # 3D content creation suite
      - calibre                       # ebook editor, viewer, converter, manager
      - chromium-browser              # web browser
      - clementine                    # music player/manager
      - copyq                         # powerful clipboard manager utility
      - create-resources              # additional resources for GIMP/Blender/Inkscape
      - darktable                     # processor for RAW images
      - dconf-editor                  # settings editor
      - easytag                       # audio file tag editor
      - filezilla                     # file transfer client
      - firefox                       # web browser
      - fritzing                      # simple circuit designer
      - fritzing-parts                # parts configuration for simple circuit designer
      - geary                         # email client
      - gimp                          # image editor
      - gimp-help-en                  # image editor documentation
      - gparted                       # partition editor
      - inkscape                      # vector graphics editor
      - kdenlive                      # video editor
      - kicad                         # electronics CAD software
      - kicad-doc-en                  # electronics CAD software documentation
      - krita                         # painting/visual art software
      - libreoffice                   # office suite
      - meld                          # diff viewer/editor
      - meshlab                       # triangular mesh editor and toolkit
      - pavucontrol                   # Pulseaudio application-level volume control
      - pdfshuffler                   # PDF page-level manipulation software
      - qalculate                     # powerful calculator utility
      - simplescreenrecorder          # screen recorder
      - vim-gtk3                      # text editor
      - vlc                           # media player
      - wireshark                     # network traffic analyser
      - xournal                       # document editor/PDF annotator
      - zeal                          # offline documentation viewer
    become: yes

  - name: install common command line apps and developer tools
    apt:
      name:
      - colordiff         # diff with colors
      - pandoc            # universal document converter
      - tree              # sort of like a recursive `ls`
      - htop              # resource monitor, sort of like a better `top`
      - nethogs           # process network usage information
      - evemu-tools       # X event toolkit
      - lm-sensors        # computer internal sensor support
      - tmux              # terminal multiplexer
      - cryptsetup        # tools for working with encrypted volumes
      - xclip             # clipboard management from the command line
      - p7zip-full        # support extracting a wider variety of archives than supported by default
      - curl              # download files from the internet
      - wget              # download files from the internet
      - gnupg2            # secure communications toolkit
      - git               # version control system
      - ansible           # configuration and deployment system
      - jekyll            # static blog-aware website generator
      - ruby-jekyll-watch # auto-reload for static blog aware site generator
      - pcregrep          # grep with PCRE instead of POSIX regular expressions
      - powertop          # Intel power management utility
      - whois             # WHOIS directory client
      - net-tools         # various networking-related tools
      - rng-tools         # TRNG interface
      - traceroute        # network path tracer
      - checkinstall      # convert software installations into OS packages
      - jq                # JSON processing with filters
      - miller            # CSV/TSV/JSON processing with filters
      - exif              # inspect EXIF data inside photos
      - restic            # incremental encrypted backups
      - love              # 2D game engine
      - rclone            # file synchronization utility for various cloud providers
      - rsync             # file synchronization utility for synchronization between computers
      - youtube-dl        # video site downloader
      - libheif-examples  # programs for working with the HEIF image format (now the default output of iPhone cameras)
      - sox               # utilities for working with audio
      - lame              # MP3 encoder and utilities
      - jupyter-notebook  # Jupyter interactive notebook with Python 3 support
      - default-jdk       # default Java compiler
      - moreutils         # useful extra command-line tools
      - w3m               # text-based web browser
    become: yes

  - name: install Yubikey 4 stuff
    apt:
      name:
      - yubikey-personalization-gui
      - yubioath-desktop
      - pcscd
      - scdaemon
      - pcsc-tools
    become: yes

  - name: install various C/C++ development tools and libraries
    apt:
      name:
      - build-essential # many useful build tools
      - cmake           # compiler-independent build system
      - ffmpeg          # media encoders/decoders
      - libjpeg-dev     # JPEG libraries
      - libpng-dev      # PNG libraries
      - libffi-dev      # foreign function interface libraries
      - rr              # recording debugger
    become: yes

  - name: install Go development tools
    apt:
      name:
      - golang
    become: yes

  - name: install database tools
    apt:
      name:
      - sqlite3
      - sqlitebrowser
      - postgresql-all
      - postgresql-client
      - postgresql-doc
      - pgadmin3
      - redis
    become: yes

  - name: install javascript development tools and common libraries
    apt:
      name:
      - nodejs
      - npm
      - yarnpkg
    become: yes

  - name: install VSCode
    block:
      - apt_key: id=BC528686B50D79E339D3721CEB3E94ADBE1229CF url=http://packages.microsoft.com/keys/microsoft.asc
      - apt_repository: repo='deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main'
      - apt: name=code update_cache=yes
    become: yes
  - name: configure VSCode
    block:
      - copy: src=files/settings.json dest=~/.config/Code/User/settings.json follow=yes
      - copy: src=files/keybindings.json dest=~/.config/Code/User/keybindings.json follow=yes

  - name: install Signal for Desktop
    block:
      - apt_key: id=DBA36B5181D0C816F630E889D980A17457F6FB06 url=https://updates.signal.org/desktop/apt/keys.asc
      - apt_repository: repo='deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main' # Signal team only maintains xenial packages, however this is designed to work for all Debian-derivatives
      - apt: name=signal-desktop update_cache=yes
    become: yes

  - name: install Python development tools and common libraries that are available as packages
    apt:
      name:
      - python3-all-dev
      - python3-pip
      - python3-wheel
      - python3-rope
      - python3-numpy
      - python3-sympy
      - python3-sklearn
      - python3-pandas
      - python3-matplotlib
      - python3-serial
      - python3-requests
      - python3-sortedcontainers
      - python3-xdo
      - python3-psycopg2
      - python3-pudb
      - flake8
      - mypy
      - python3-scipy
      - python3-plotly
      - python3-seaborn
      - python3-bs4
      - python3-pexpect
      - python3-pyperclip
      - python3-venv
      - python3-q
      - virtualenvwrapper
      - twine
    become: yes

  - name: install Virtualbox
    block:
      - apt: name=virtualbox
      - user: name={{ user_name }} groups=vboxusers append=yes  # needed for USB access within VMs
        become: yes

  - name: install ZSH and make it the default shell
    block:
      - apt:
          name:
          - zsh
          - zsh-syntax-highlighting
          - zsh-doc
          - zgen
          - socat
          - python3-psutil
          - python3-pygit2
          - powerline
      - user: name={{ user_name }} shell=/bin/zsh
    become: yes
  - name: configure ZSH
    copy: src=files/.zshrc dest=~/.zshrc follow=yes

  - name: configure Vim
    copy: src=files/.vimrc dest=~/.vimrc follow=yes

  - name: install various system administration scripts
    copy: src=files/bin/ dest=~/.local/bin follow=yes

  # TODO: install these
  #- name: install basic audio/music packages
  #  apt:
  #    name:
  #    - qjackctl     # JACK audio control/configuration panel
  #    - vmpk         # virtual MIDI keyboard
  #    - lmms         # simple sequencer/DAW
  #    - jalv         # plugin host for LV2 audio plugins
  #    - calf-plugins # collection of useful LV2 audio plugins
  #    - so-synth-lv2 # LV2 synthesizer plugins
  #    - caps         # C* audio plugin suite
  #    - zynaddsubfx  # subtractive synthesizer
  #    - ams          # modular synthesizer
  #    - qmidiroute   # MIDI re-routing utility
  #    - qmidiarp     # MIDI arpeggiator
  #    - hydrogen     # drum machine/sequencer
  #    - ardour       # fully-featured DAW
  #  become: yes

  - name: install FireJail and set it up with the basic profiles
    block:
      - shell:
          cmd: firecfg
          creates: /usr/local/bin/firefox
        become: yes
      - file: path=/usr/local/bin/zeal state=absent  # Firejail isolation breaks Zeal, because Firejail's Zeal profile disallows network access, so remove Firejail's Zeal shortcut # TODO: review this again in 2021
        become: yes

  - name: install and set up Docker
    block:
      - apt: name=docker.io
        become: yes
      - apt: name=docker-compose
        become: yes
      - user: name={{ user_name }} groups=docker append=yes
        become: yes

  # UPGRADEABLE: LAST UPDATE 2020-07-12
  - name: install Arduino CLI
    block:
      - get_url:
          checksum: sha512:efebdecd881da4cbb6a6351682fab07ac3199474168c6b693f3a1f8b8b072387ba83b979e09e2ddfd03e49e8cff767c56bc77f0b78eb143af98215aa992cdf6f
          dest: "/tmp/arduino-cli-linux.tar.xz"
          url: https://downloads.arduino.cc/arduino-cli/arduino-cli_0.11.0_Linux_64bit.tar.gz
      - unarchive: remote_src=yes dest=/tmp/ src="/tmp/arduino-cli-linux.tar.xz"
      - copy: remote_src=yes src=/tmp/arduino-cli dest=~/.local/bin/arduino-cli
      - shell:
          cmd: arduino-cli core install arduino:avr
          creates: ~/.arduino15/packages/arduino/hardware/avr
      - shell:
          cmd: arduino-cli core install arduino:mbed
          creates: ~/.arduino15/packages/arduino/hardware/mbed
      - user: name={{ user_name }} groups=dialout append=yes
        become: yes

  - name: configure XFCE
    block:
      # install some extra XFCE stuff such as clipman
      - apt: name=xfce4-goodies

      # set theme to Numix
      - xfconf: channel=xsettings property=/Net/ThemeName value_type=string value=Numix
      - xfconf: channel=xfwm4 property=/general/theme value_type=string value=Numix

      # disable Alt + Drag to move a window, this interferes with apps like Blender that use that for their own purposes
      - xfconf: channel=xfwm4 property=/general/easy_click value_type=string value=dummy state=absent

      # show window previews in Alt + Tab window switcher
      - xfconf: channel=xfwm4 property=/general/cycle_preview value_type=bool value=true

      # set Win + Q to open Whisker menu
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Primary>Escape" value_type=string value=dummy state=absent
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Super>q" value_type=string value=xfce4-popup-whiskermenu

      # set Win + C to open Qalculate
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Super>c" value_type=string value=qalculate

      # set Win + E to open VSCode
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Super>e" value_type=string value=code

      # set Win + F to open file manager
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Super>f" value_type=string value="thunar Dropbox"

      # set Win + S to open Clipman
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Super>s" value_type=string value=xfce4-popup-clipman

      # set Win + / to toggle maximize
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Super>slash" value_type=string value=maximize_window_key

      # set Win + F11 to toggle fullscreen
      - xfconf: channel=xfce4-keyboard-shortcuts property="/commands/custom/<Super>F11" value_type=string value=fullscreen_key

      # set laptop lid close to suspend the laptop, both on battery and when plugged in
      - xfconf: channel=xfce4-power-manager property=/xfce4-power-manager/lid-action-on-battery value_type=int value=1
      - xfconf: channel=xfce4-power-manager property=/xfce4-power-manager/lid-action-on-ac value_type=int value=1

      # don't autoplay any type of optical disks
      - xfconf: channel=thunar-volman property=/autoplay-audio-cds/enabled value_type=bool value=false
      - xfconf: channel=thunar-volman property=/autoplay-video-cds/enabled value_type=bool value=false

      # show specific columns in Thunar in a specific order
      - xfconf: channel=thunar property=/last-details-view-visible-columns value_type=string value=THUNAR_COLUMN_DATE_MODIFIED,THUNAR_COLUMN_GROUP,THUNAR_COLUMN_NAME,THUNAR_COLUMN_OWNER,THUNAR_COLUMN_PERMISSIONS,THUNAR_COLUMN_SIZE,THUNAR_COLUMN_TYPE
      - xfconf: channel=thunar property=/last-details-view-column-order value_type=string value=THUNAR_COLUMN_NAME,THUNAR_COLUMN_SIZE,THUNAR_COLUMN_SIZE_IN_BYTES,THUNAR_COLUMN_TYPE,THUNAR_COLUMN_DATE_MODIFIED,THUNAR_COLUMN_OWNER,THUNAR_COLUMN_GROUP,THUNAR_COLUMN_PERMISSIONS,THUNAR_COLUMN_DATE_ACCESSED,THUNAR_COLUMN_MIME_TYPE

      # use setxkbmap to swap CapsLock and Escape upon login
      - copy: src=files/SwapCapsLockAndEscape.desktop dest=~/.config/autostart/SwapCapsLockAndEscape.desktop

      # load top panel configuration profile (generated by using `xfce4-panel-profiles save xfce-panel-config.tar.bz2`, this saves the current top panel configuration)
      - copy: src=files/xfce-panel-config.tar.bz2 dest=/tmp/xfce-panel-config.tar.bz2
      - shell: xfce4-panel-profiles load /tmp/xfce-panel-config.tar.bz2

  - name: configure Git
    git_config: name={{ item.name }} scope=global value={{ item.value }}
    with_items:
      - { name: "rerere.enabled", value: "true" }               # enable reuse of recorded hunk conflict resolutions
      - { name: "push.default", value: "matching" }             # use matching behaviour in pushes
      - { name: "user.name", value: "{{ real_name }}" }         # user's real name
      - { name: "user.email", value: "{{ email }}" }            # user's real name
      - { name: "diff.tool", value: "meld" }                    # diff viewer utility
      - { name: "core.pager", value: "less --chop-long-lines" } # disable word wrap in git diff

  - name: disable unnecessary network-facing services such as Avahi/Bonjour and CUPS
    block:
      - service: name=avahi-daemon.service enabled=no state=stopped
        become: yes
      - service: name=avahi-daemon.socket enabled=no state=stopped
        become: yes
      - service: name=cups enabled=no state=stopped
        become: yes
      - apt: name=kdeconnect state=absent
        become: yes

  - name: disable occasionally-used services that take up a lot of resources
    block:
      - service: name=snapd enabled=no state=stopped
        become: yes
      - service: name=postgresql enabled=no state=stopped
        become: yes
      - service: name=redis-server enabled=no state=stopped
        become: yes

  - name: enable UFW so it runs on boot, the default ruleset denies all incoming traffic and allows all outgoing traffic (check with "sudo ufw status verbose")
    ufw: state=enabled
    become: yes
